apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: exuz4j232-dotnet-basic 
  janus-idp.io/tekton: exuz4j232-dotnet-basic
  backstage.io/kubernetes-id: exuz4j232-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: exuz4j232-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  